### ISSUE TITLE
Chat Solution

### ISSUE THREAD

**Issue by tudorian** [flavour/eden#1087]
Is there any chat solution that can be integrated with Sahana.

Thank you

**Comment by ptressel** [comment]
Hi, Tudorian!

Yes, there was a GSoC project last year to integrate a chat server -- it uses Openfire.

http://eden.sahanafoundation.org/wiki/Event/2014/GSoC/Chat

**Comment by tudorian** [comment]
Thank you very much!

**Comment by tudorian** [comment]
I manage to integrate openfire with sahana DB but the chat box does not appear in Sahana. I am using the default template and configured the chat  options in the 000_config.py in the Eden\models folder.

A sample below.

settings.base.chat_server = {
   "ip": "127.0.0.1",
   "port": 7070,
   "name": "sahana",
#	# Default group everyone is added to
   "groupname" : "everyone",
   "server_db" : "openfire",
#   # These settings fallback to main DB settings if not specified
#   # Only mysql/postgres supported
    "server_db_type" : "mysql",
    "server_db_username" : "sahana",
    "server_db_password": "******",
    "server_db_port" : 3306,
    "server_db_ip" : "127.0.0.1",
   }

Am I missing something ?

**Comment by graeme-f** [comment]
Do you have any errors? Check firebug, or the equivalent on your browser,
to see what the return code is, You can also check to see if you have any
new trace-back in the error folder. I'm away from my dev machine so I am
not able to give you much support at the moment, sorry, but the most likely
cause is an error so you will nee to look for that. The most common cause
of error are either javascript error or a error response from Sahana.

**Comment by tudorian** [comment]
I checked the generated HTML file, no errors are present.

I noticed that S3.chat.js is not loaded . That why I supposed there is a configuration problem.

**Comment by tudorian** [comment]
I identified some problem in the Sahana - Debug Mode . In the production installation still no chat 

TypeError: deps is undefined
http://127.0.0.1:8000/eden/static/scripts/converse.nojquery.js
Line 405

TypeError: geti18nSetting is not a function
http://127.0.0.1:8000/eden/static/scripts/S3/s3.chat.js
Line 10

**Comment by tudorian** [comment]
I found the problem
there is a bug in  s3.chat.js

  i18n: geti18nSetting(), should be   i18n: geti18nSetting,

**Comment by flavour** [comment]
Thankyou - fix committed :)

**Comment by ptressel** [comment]
Cool -- thank you, Tudor!

**Comment by tudorian** [comment]
You' re wellcome :)
