### ISSUE TITLE
Sahana Chat Issues

### ISSUE THREAD

**Issue by tudorian** [flavour/eden#1092]
Some times the following error appears when the chat windows is loaded
TypeError: deps is undefined
if (!deps.splice) {

file : converse.nojquery.js line 405 col 12

    define = function (name, deps, callback) {

        //This module may not have dependencies
        if (!deps.splice) {
            //deps is not an array, so probably means
            //an object literal or factory function for
            //the value. Adjust args.
            callback = deps;
            deps = [];
        }

        if (!hasProp(defined, name) && !hasProp(waiting, name)) {
            waiting[name] = [name, deps, callback];
        }
    };

**Comment by flavour** [comment]
This looks like an upstream issue...this file is vanilla upstream as far as I know.
I would talk to the developrs of that project to get that resolved...and then please pass on the results to us here so that we update the file accordingly.

**Comment by tudorian** [comment]
ok great!

**Comment by tudorian** [comment]
i have a new version of converse.jquery.js. How can i generate the minified version of sahana chat?

**Comment by flavour** [comment]
Did you get this from upstream? General new version or specific fix for us?

1st test it using ?debug=1
If it works well then you can also compile & retest minified:
http://eden.sahanafoundation.org/wiki/DeveloperGuidelines/Minify

or else send it to me for me to include/compile

**Comment by tudorian** [comment]
Yes from upstream. I tested it on my local deployment but without success.  I think there is a javascript loadin problem because sometimes the chat works and sometimes it doesn't

**Comment by graeme-f** [comment]
You need to have the nojquery version because a conflict will occur when
both converse and web2py try and load their version of jquery

**Comment by tudorian** [comment]
I still cannot figure out why the problem appears. Sometimes a value that is passed to converse  is null and a method of converse tries to access a property of that null object

**Comment by tudorian** [comment]
The problem appears in converse.nojquery when the fastclick
