### ISSUE TITLE
Help deploying

### ISSUE THREAD

**Issue by schlos** [flavour/eden#1158]
Is there somebody who can offer help in deploying Sahana Eden to our servers?
We want to use this for coordinating in helping refugees in Croatia.

In return I offer quality testing and reporting of all bugs we found when using Eden.

Cheers,
Miroslav

**Comment by nursix** [comment]
Hello @schlos - please contact me outside GitHub under dominic@aidiq.com

**Comment by nursix** [comment]
@flavour please close, I'll take care of that.
